# Site settings
title: Mohammad Mahmoodian
description: A blog about Mohammad Mahmoodian
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mohammad Mahmoodian
user_description: I am an Electrical Engineer that has good experience in software development specifically blockchain development 
user_title: Developer
email: mahmoodian@ut.ac.ir
twitter_username: https://twitter.com/momaee1
github_username: https://github.com/momaee
instagram_username: https://www.instagram.com/mo_ma_ee
linkedin_username: https://www.linkedin.com/in/mohammad-mahmoodian-397a508a/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
